#!/usr/bin/env python3

import argparse
import logging
import os
import re
import sys

from core import atop
from core import common


def load_atop(input_filepath, requested_labels):
    output = []

    logging.info("Loading atop file '{0}'".format(input_filepath))
    since_boot = True
    with open(input_filepath, "r") as f:
        for line in f:
            line = line.strip()
            label = line[0:3]

            if label == "RES":
                since_boot = True

            elif label == "SEP":
                since_boot = False

            else:
                logging.debug(line)
                fields = atop.split_line(line)

                if label == "NET":
                    if fields[atop.NET_INTERFACE_FIELD] == "upper":
                        label = "NET-upper"

                if requested_labels and label not in requested_labels:
                    continue

                if label in atop.MAPPING:
                    headers = atop.MAPPING[label]

                    entry = {
                        headers[i]: re.sub(r'^\((.*)\)$', r'\1', fields[i])
                        for i in range(0, len(headers))
                        if headers[i] != ""}

                    if len(entry) > 0:
                        logging.debug(common.prettify(entry))
                        entry["label"] = label
                        entry["since_boot"] = since_boot
                        output.append(entry)

    return output


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        '-i', dest='input_filepath', action='store',
        help="Input atop file (e.g. capture.txt)")
    parser.add_argument(
        '-P', dest='labels', action='store',
        default="ALL",
        help="Labels to process, comma separated (e.g. -P CPU,MEM,PRC)")
    parser.add_argument(
        '-v', dest='verbose', action='store_true',
        default=False,
        help="Print details")
    args = parser.parse_args()

    if not args.input_filepath:
        parser.print_help(file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(args.input_filepath):
        logging.error("Couldn't find file '{0}'".format(
            args.input_filepath))
        sys.exit(1)

    if args.labels != "ALL":
        requested_labels = set(args.labels.strip().split(","))
        for label in requested_labels:
            if label not in atop.MAPPING:
                logging.error("Label '{0}' not supported".format(label))
                sys.exit(1)
    else:
        requested_labels = None

    if args.verbose:
        common.configure(logging.DEBUG)
    else:
        common.configure(logging.INFO)

    output = load_atop(args.input_filepath, requested_labels)

    print(common.prettify(output))
